web:
  build: ./app
  command: ["docker build --rm -t t206cv ./app", "docker run -p 8080:5000 --name app t206cv", "python app.py"]
  working_dir: /app
  environment:
    PORT: 8080
  ports:
    - '8080:5000'
shell:
  build: ./app
  command: bash
  working_dir: /app
  environment:
    PORT: 8080
  ports:
    - '8080:5000'
  volumes:
    - '.:/app'
