app:
    build: app
#    volumes_from:
#        - data

nginx:
    build: nginx
    ports:
        - "1337:80"
    links:
        - app

#data:
#    build: data
#    command: echo 'Data Container'
#    volumes:
#        - /app/dbdata
